# Generated by Django 4.1 on 2022-11-02 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_favorite_id_alter_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Не может быть меньше 1 минуты'), django.core.validators.MaxValueValidator(60, 'Не может быть больше 60 минут')], verbose_name='Время приготовления (минуты)'),
        ),
    ]
