# Generated by Django 4.1 on 2022-10-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='not_follow_yourself',
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('author')), _negated=True), name='cant_follow_yourself'),
        ),
    ]
